package it.polimi.ingsw.GC_06.model.BonusMalus;

/**
 * Created by giuseppe on 6/5/17.
 */
public enum ActionType {
    PRODUCTION_ACTION,HARVEST_ACTION,TOWERACTION,PAYCARDACTION,RESOURCEACTION,
    ENDACTION,TOWER_ACTION,END_GAME,PLAY_HERO_CARD,GENERAL,BOARD_ACTION_ON_TOWER,
    BOARD_ACTION_ON_MARKET,POWER_UP_FAMILY_MEMBER

}
