package it.polimi.ingsw.GC_06.model.State;

/**
 * Created by massimo on 03/06/17.
 * @author massimo
 * All the states
 */
public enum StateName {
    IDLE, MEMBER_ON_TOWER, CHOOSING_PAYMENT, CARD_READY, CARD_TO_USER, CHOOSING_CARD, MEMBER_ON_PROFHARV, CHOOSING_PRODHARV_CARDS,
    MEMBER_ON_MARKETCOUNSIL, CHOOSING_PARCHMENT, CHOOSING_SUPPORT_VATICAN, TURN_ACTION_COMPLETED
}
