package it.polimi.ingsw.GC_06.model.State;

/**
 * Created by massimo on 03/06/17.
 */
public enum TransitionType {
    ACTION_ON_TOWER,PAY_CARD,PICK_CARD,USR_PICK_CARD,ACTION_ON_PRODHARV,START_PRODHARV,
    REQUESTED_CARDS, PAYCARD,ACTION_ON_MARKET_COUNSIL, EXECUTE_EFFECT, USR_MULTIPLEPAYMENT,
    USR_PRODHARVTRANSFORM,CHOOSING_PARCHMENT, CHOOSING_CARD, ROUNDFINISHED, ENDGAME
}