package it.polimi.ingsw.GC_06.model.State;

/**
 * Created by massimo on 03/06/17.
 */
public enum TransitionType {
    ACTION_ON_TOWER, ASK_PAYMENT, PAY_CARD, PICK_CARD, BONUS_CARD,ACTION_ON_PRODHARV,START_PRODHARV,
    PRODHARV, ACTION_ON_MARKETCOUNSIL, EXECUTE_EFFECT, CHOOSE_PARCHMENT,
    PARCHMENT_CHOICE_DONE, SIDE_WITH_VATICAN, PAY_VATICAN, GET_EXCOMUNICATION, ENDTURN, ENDGAME
}