package it.polimi.ingsw.GC_06.model.State;

/**
 * Created by massimo on 03/06/17.
 */
public enum TransitionType {
    ADDFAMILYMEMBER, PICKCARD, PAYCARD, EXECUTEEFFECT, USR_MULTIPLEPAYMENT, PRODHARV, USR_PRODHARVTRANSFORM,CHOOSING_PARCHMENT, CHOOSING_CARD
}
